name = "aoc202405a"
description = "AoC Day 5 problem 1"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202405a"]
