name = "main"
description = "AoC problem"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["main"]
