name = "aoc202411b"
description = "Aoc 10 2"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <theovosse@gmx.com>"]
maintainers-logins = ["theovosse"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202411b"]
