name = "aoc202410a"
description = "AoC Day 10 problem 1"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <theovosse@gmx.com>"]
maintainers-logins = ["theovosse"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202410a"]
