name = "aoc202412a"
description = "aoc 12 1"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202412a"]
