name = "aoc202401a"
description = "Exercise 1 A"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202401a"]
