name = "aoc202406b"
description = "AoC day 6 problem 2"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202406b"]
