name = "aoc202402a"
description = "AOC problem 2 A"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202402a"]
