name = "aoc202409b"
description = "AoC day 9 problem 2"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202409b"]
