name = "aoc202407a"
description = "AoC day 7 problem 1"
version = "0.1.0-dev"

authors = ["TGV"]
maintainers = ["TGV <email>"]
maintainers-logins = ["xxx"]
licenses = "custom-none"
website = ""
tags = []

executables = ["aoc202407a"]
