/* Configuration for aoc202409a generated by Alire */
#ifndef AOC202409A_CONFIG_H
#define AOC202409A_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "aoc202409a"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
